version: '3.8'
services:
  mediawiki:
    image: mediawiki
    container_name: mediawiki
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html
    environment:
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_USER: root
      MEDIAWIKI_DB_PASSWORD: example
      MEDIAWIKI_DB_NAME: my_wiki
  db:
    image: mariadb
    container_name: mediawiki_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_wiki
