version: "3.8"

services:
  web:
    build:
      context: .
    container_name: WebPersonalPHP
    volumes:
      - ./php:/var/www/html
    ports:
      - "8083:80"  
    depends_on:
      - db

  db:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: marin          
      MYSQL_DATABASE: proyectos            
      MYSQL_USER: marin                  
      MYSQL_PASSWORD: marin             
    volumes:
      - ./db:/docker-entrypoint-initdb.d   
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db                    
      PMA_PORT: 3306
    ports:
      - "8084:80"                   
    depends_on:
      - db
