services:
  mysql:
    container_name: moodle_database
    image: mysql
    ports:
      - 8081:3306
    restart: always
    volumes:
      - C:/Moodle/Moodle_db:/var/lib/mysql
      - C:/Moodle/Moodle_data:/var/www/moodledata
    environment:
      MYSQL_ROOT_PASSWORD: $SQL_ROOT_PWD
      MYSQL_USER: $SQL_USER
      MYSQL_PASSWORD: $SQL_PASSWD
      MYSQL_DATABASE: $SQL_DBNAME
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    networks:
      net: 
        ipv4_address: 192.168.0.99

  web:
    build:
      context: .
    container_name: moodle_www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    ports:
      - 8081:80

    networks:
      net:
        ipv4_address: 192.168.0.100

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
